name: Upload Website

on:
  push:
    branches:
      - main  # Ensure the correct branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4  # Use the latest stable version of the checkout action

      # Step 2: Debugging the SOURCE_DIR
      - name: Debug Source Directory
        run: |
          echo "SOURCE_DIR content:"
          ls -al "Resume Website"

      # Step 3: Upload to S3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0  # Stable release
        with:
          args: --follow-symlinks --delete  # Avoid --acl public-read for private files
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  # Your bucket name stored in GitHub Secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key
          AWS_REGION: 'us-east-1'  # Region matching your bucket
          SOURCE_DIR: 'Resume Website'  # Your local source directory
