name: Upload Website

on:
  push:
    branches:
      - main  # Ensure the correct branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Debug the source directory
      - name: Debug Source Directory
        run: |
          echo "SOURCE_DIR content:"
          ls -al "."

      # Step 3: Upload to S3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --follow-symlinks --delete  # No unnecessary prefixes
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  # Ensure only the bucket name is set (e.g., clauderesume)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  # Ensure region matches your bucket
          SOURCE_DIR: '.'  # Using the current directory (adjust as necessary)
