name: Upload website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Upload the website to the S3 bucket
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --follow-symlinks --delete s3://${{ secrets.AWS_S3_BUCKET }}  # Ensure correct bucket path here
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'Resume Website'  # This is the directory you want to sync to S3 (adjust as necessary)
