name: Upload website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Debug step to verify S3 bucket name
      - name: Debug S3 Bucket
        run: echo "S3 Bucket: ${{ secrets.AWS_S3_BUCKET }}"

      # Step 3: Upload to S3 using s3-sync-action
      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'Resume Website'
