name: Upload Website

on:
  push:
    branches:
      - main  # Ensure the correct branch (adjust if necessary)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4  # Use the latest stable version

      # Debugging step to check AWS_S3_BUCKET value
      - name: Debug AWS_S3_BUCKET
        run: echo "AWS_S3_BUCKET is ${{ secrets.AWS_S3_BUCKET }}"

      # Step 2: Upload to S3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --follow-symlinks --delete ${{ secrets.AWS_S3_BUCKET }}  # Corrected syntax
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: 'us-east-1'   # Adjust region as needed
          SOURCE_DIR: 'Resume Website'  # Adjust to your source directory
